### ISSUE TITLE
wavesurferの読み込みが失敗して動かない

### ISSUE THREAD

**Issue by Mindful** [koniwa/hachiue#202]
今日hachiueを開いてみたら、wavesurferの必要なファイルの読み込みに失敗して動かなくなっているようです。UIの一部は操作できますが、音声ファイルのアップロードなどはできないです。
<img width="1360" alt="Screen Shot 2023-10-08 at 20 46 30" src="https://github.com/koniwa/hachiue/assets/2897172/8b478a96-6a4d-405f-8647-8eef67fd4ebc">

ローカルで最新のコミットを取り消してビルドしたら問題が消えるので、このhttps://github.com/koniwa/hachiue/commit/ca61825996bf36836d1dd76152bb054130f710ac コミットが原因かと思います。

**Comment by shirayu** [comment]
コメントありがとうございます！
wavesurfer 6 -> 7でのbreaking changeが原因でした．

https://github.com/katspaugh/wavesurfer.js/releases/tag/7.0.0

ひとまず6に戻して動作することを確認しました ( 25718b0580158229af2dadce806a6418a55fa7a8 )
